import { resolve } from 'node:path';
import { createCodeBuilder, createFileEmitter, generateCommandTree } from 'padrone/codegen';
import type { DiscoverySource } from '../codegen/discovery.ts';
import { discoverCli } from '../codegen/discovery.ts';
import { template } from '../codegen/template.ts';
import type { GeneratorContext } from '../codegen/types.ts';
import type { PadroneActionContext } from '../types.ts';

interface WrapArgs {
  command: string;
  source?: DiscoverySource;
  output?: string;
  depth?: number;
  dryRun?: boolean;
  overwrite?: boolean;
}

export async function runWrap(args: WrapArgs, ctx: PadroneActionContext) {
  const { output, error } = ctx.runtime;
  const command = args.command;
  const sources: DiscoverySource[] = args.source ? [args.source] : ['help'];
  const outDir = resolve(args.output || `./src/${command}`);

  output(`Discovering ${command} CLI structure...`);

  const result = await discoverCli({
    command,
    sources,
    depth: args.depth,
    log: {
      info: (msg) => output(msg),
      warn: (msg) => output(`  warn: ${msg}`),
      error: (msg) => error(msg),
      success: (msg) => output(msg),
    },
  });

  if (result.warnings.length > 0) {
    output('');
    output('Warnings:');
    for (const warn of result.warnings) {
      output(`  - ${warn}`);
    }
  }

  const subcommandCount = countSubcommands(result.command);
  const optionCount = countOptions(result.command);

  output('');
  output(`Discovered: ${subcommandCount} commands, ${optionCount} options (${result.invocations} invocations)`);
  output('');

  // Generate the wrapper project
  const emitter = createFileEmitter({
    outDir,
    header: `// Generated by \`padrone wrap ${command}\` — do not edit manually`,
    overwrite: args.overwrite,
    dryRun: args.dryRun,
  });

  const genCtx: GeneratorContext = {
    outDir,
    createCodeBuilder,
    emitter,
    template,
    log: {
      info: (msg) => output(msg),
      warn: (msg) => output(`  warn: ${msg}`),
      error: (msg) => error(msg),
      success: (msg) => output(msg),
    },
  };

  generateCommandTree(result.command, genCtx, { wrap: { command } });

  const emitResult = await emitter.emit();

  if (emitResult.errors.length > 0) {
    for (const err of emitResult.errors) {
      error(`Failed to write ${err.file}: ${err.error.message}`);
    }
    return;
  }

  if (args.dryRun) {
    output('Dry run — files that would be written:');
  } else {
    output('Files written:');
  }

  for (const file of emitResult.written) {
    output(`  ${file}`);
  }

  if (emitResult.skipped.length > 0) {
    output('');
    output('Skipped (already exist, use --overwrite to replace):');
    for (const file of emitResult.skipped) {
      output(`  ${file}`);
    }
  }
}

function countSubcommands(cmd: { subcommands?: { subcommands?: any[] }[] }): number {
  let count = 0;
  if (cmd.subcommands) {
    count += cmd.subcommands.length;
    for (const sub of cmd.subcommands) {
      count += countSubcommands(sub);
    }
  }
  return count;
}

function countOptions(cmd: { arguments?: unknown[]; subcommands?: any[] }): number {
  let count = cmd.arguments?.length || 0;
  if (cmd.subcommands) {
    for (const sub of cmd.subcommands) {
      count += countOptions(sub);
    }
  }
  return count;
}
